import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Codebase graph — Software Discovery",
  description:
    "Interactive knowledge graph of this project's source, generated by Graphify from the codebase.",
};

/**
 * Hosts the interactive knowledge graph that Graphify emits (graph.html) for this
 * project. Graphify is a local, tree-sitter based tool (https://github.com/Graphify-Labs/graphify)
 * that turns the codebase into a traversable graph; we publish its self-contained
 * HTML output to /graphify/ and surface it here in an iframe so it renders with no
 * external CDN or JS dependency.
 */
export default function GraphPage() {
  return (
    <div className="flex min-h-dvh flex-col bg-background">
      <header className="border-b border-border px-4 py-3 sm:px-6">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-4">
          <div className="min-w-0">
            <h1 className="text-lg font-semibold tracking-[-0.01em]">Codebase knowledge graph</h1>
            <p className="mt-0.5 truncate text-13 text-muted-foreground">
              Generated by{" "}
              <a
                href="https://github.com/Graphify-Labs/graphify"
                target="_blank"
                rel="noreferrer"
                className="font-medium text-primary hover:text-primary-hover"
              >
                Graphify
              </a>{" "}
              from the project source — pan, zoom, and click a node to inspect it.
            </p>
          </div>
          <Link
            href="/graphify/graph.html"
            target="_blank"
            rel="noreferrer"
            className="shrink-0 text-13 font-medium text-primary hover:text-primary-hover"
          >
            Open in new tab ↗
          </Link>
        </div>
      </header>

      <div className="min-h-0 flex-1">
        <iframe
          src="/graphify/graph.html"
          title="Codebase knowledge graph"
          className="h-full w-full border-0"
          style={{ minHeight: "calc(100dvh - 57px)" }}
        />
      </div>
    </div>
  );
}
